-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 11:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema capstoneCovidReporting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `capstoneCovidReporting`;

-- -----------------------------------------------------
-- Schema capstoneCovidReporting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capstoneCovidReporting` DEFAULT CHARACTER SET latin1;
USE `capstoneCovidReporting` ;

-- -----------------------------------------------------
-- Table `capstoneCovidReporting`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneCovidReporting`.`roles` (
  `RoleId` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(25) NOT NULL,
  `can_write` BIT NOT NULL,
  `can_view` BIT NOT NULL,
  `can_manage` BIT NOT NULL,
  PRIMARY KEY (`RoleId`))
  ENGINE = InnoDB;
  
-- -----------------------------------------------------
-- Table `capstoneCovidReporting`.`organisations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneCovidReporting`.`organisations` (
  `organisation_id` INT NOT NULL AUTO_INCREMENT,
  `organisationName` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`organisation_id`))
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capstoneCovidReporting`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneCovidReporting`.`users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(256) NOT NULL,
  `Password` VARCHAR(256) NOT NULL,
  `Email` VARCHAR(256) NOT NULL,
  `FirstName` VARCHAR(256) NOT NULL,
  `LastName` VARCHAR(256) NOT NULL,
  `Active` BIT NOT NULL,
  `Role` INT NOT NULL,
  `Organisation` INT NOT NULL,
  PRIMARY KEY (`UserID`),
CONSTRAINT `fk_user_role`
    FOREIGN KEY (`Role`)
    REFERENCES `capstoneCovidReporting`.`roles` (`RoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_user_organisation`
    FOREIGN KEY (`Organisation`)
    REFERENCES `capstoneCovidReporting`.`organisations` (`organisation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capstoneCovidReporting`.`UUID_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneCovidReporting`.`uuid_map` (
  `ID` int not null auto_increment,
  `UserID` int NOT NULL,
  `Iterations` INT NOT NULL,
  `Salt` VARCHAR(32) NOT NULL,
  `UUID` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ID`),
CONSTRAINT `fk_uuid_username`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstoneCovidReporting`.`users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `unique_userid` UNIQUE(`UserID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capstoneCovidReporting`.`covid_test_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneCovidReporting`.`covid_test_results` (
  `CovidTestResultID` INT NOT NULL AUTO_INCREMENT ,
  `ResultDate` DATE NOT NULL,
  `SubmissionDate` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `NumberTestsTaken` INT NOT NULL,
  `NumberTestsPositive` INT NOT NULL,
  `NumberTestsInconclusive` INT NOT NULL DEFAULT 0,
  `PositivityRate` DOUBLE NOT NULL,
  `ReporterID` INT NOT NULL,
  `Notes` VARCHAR(256),
  PRIMARY KEY (`CovidTestResultID`),
  CONSTRAINT `fk_test_result_reporter1`
    FOREIGN KEY (`ReporterID`)
    REFERENCES `capstoneCovidReporting`.`users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `capstoneCovidReporting`.`covid_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneCovidReporting`.`covid_reports` (
  `CovidReportID` INT NOT NULL AUTO_INCREMENT,
  `ReportDate` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `oneDayDifference` INT NOT NULL,
  `sevenDayDifference` INT NOT NULL,
  `fourteenDayDifference` INT NOT NULL,
  `totalCases` INT NOT NULL,
  `totalActiveCases` INT NOT NULL,
  `totalRecovered` INT NOT NULL,
  `totalDeaths` INT NOT NULL,
  `positivityRate` DOUBLE NOT NULL,
  `Notes` VARCHAR(256),
  PRIMARY KEY (`CovidReportID`))
ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `capstoneCovidReporting`.`covid_report_recipients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneCovidReporting`.`covid_report_recipients` (
  `CovidReportID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`CovidReportID`, `UserID`),
  CONSTRAINT `fk_report_recipients_report1`
    FOREIGN KEY (`CovidReportID`)
    REFERENCES `capstoneCovidReporting`.`covid_reports` (`CovidReportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_recipients_users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstoneCovidReporting`.`users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `capstoneCovidReporting`.`covid_report_covid_test_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneCovidReporting`.`covid_report_covid_test_results` (
  `CovidReportID` INT NOT NULL,
  `CovidTestResultID` INT NOT NULL,
  PRIMARY KEY (`CovidReportID`, `CovidTestResultID`),
  CONSTRAINT `fk_report_results_report1`
    FOREIGN KEY (`CovidReportID`)
    REFERENCES `capstoneCovidReporting`.`covid_reports` (`CovidReportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_results_tests1`
    FOREIGN KEY (`CovidTestResultID`)
    REFERENCES `capstoneCovidReporting`.`covid_test_results` (`CovidTestResultID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

--
--
--

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- roles
INSERT INTO `roles` (`RoleName`,`can_write`,`can_view`,`can_manage`) VALUES ('System Administrator', 1, 1, 1);
INSERT INTO `roles` (`RoleName`,`can_write`,`can_view`,`can_manage`) VALUES ('Reporter', 1, 0, 0);
INSERT INTO `roles` (`RoleName`,`can_write`,`can_view`,`can_manage`) VALUES ('Recipient', 0, 1, 0);

-- organisations
INSERT INTO `organisations` (`organisationName`) VALUES ('unassigned');
INSERT INTO `organisations` (`organisationName`) VALUES ('Alpine Village Jasper');
INSERT INTO `organisations` (`organisationName`) VALUES ('Athabasca Hotel');
INSERT INTO `organisations` (`organisationName`) VALUES ('Bear Hill Lodge');
INSERT INTO `organisations` (`organisationName`) VALUES ('Beckers Chaletes');
INSERT INTO `organisations` (`organisationName`) VALUES ('Cocos" Cafe');
INSERT INTO `organisations` (`organisationName`) VALUES ('Decore Hotels(Maligne Lodge)');
INSERT INTO `organisations` (`organisationName`) VALUES ('Decore Hotels(Tonquin Inn)');
INSERT INTO `organisations` (`organisationName`) VALUES ('Decore Hotels(Wicked Cup)');
INSERT INTO `organisations` (`organisationName`) VALUES ('Jasper House(Bungalows)');
INSERT INTO `organisations` (`organisationName`) VALUES ('Jasper Raft Tours');
INSERT INTO `organisations` (`organisationName`) VALUES ('Jasper Sky Tram');
INSERT INTO `organisations` (`organisationName`) VALUES ('Jasper Source for Sports');
INSERT INTO `organisations` (`organisationName`) VALUES ('Journey Bike Guides INC');
INSERT INTO `organisations` (`organisationName`) VALUES ('Karouzos Steakhouse');
INSERT INTO `organisations` (`organisationName`) VALUES ('Liquor Lodge(1)');
INSERT INTO `organisations` (`organisationName`) VALUES ('Liquor Lodge(2)');
INSERT INTO `organisations` (`organisationName`) VALUES ('Maligne Rafting Adventures');
INSERT INTO `organisations` (`organisationName`) VALUES ('Patricia Lake Bungalows');
INSERT INTO `organisations` (`organisationName`) VALUES ('Royal Canadian Legion Branch 31');
INSERT INTO `organisations` (`organisationName`) VALUES ('Snowdome Coffee Bar');
INSERT INTO `organisations` (`organisationName`) VALUES ('Spa Jasper');
INSERT INTO `organisations` (`organisationName`) VALUES ('Tekarra Restaurant');
INSERT INTO `organisations` (`organisationName`) VALUES ('Mount Robson Inn');
INSERT INTO `organisations` (`organisationName`) VALUES ('Wildlife Childcare');
INSERT INTO `organisations` (`organisationName`) VALUES ('Community Outreach');
INSERT INTO `organisations` (`organisationName`) VALUES ('Operations Facility');
INSERT INTO `organisations` (`organisationName`) VALUES ('Bylaw Office');
INSERT INTO `organisations` (`organisationName`) VALUES ('Jasper Fitness & Aquatic Center');
INSERT INTO `organisations` (`organisationName`) VALUES ('Famoso');
INSERT INTO `organisations` (`organisationName`) VALUES ('Covid Report Admin/Testing');

-- USERS
-- system admin
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('admin','10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a','jaspercovidreporting+admin@gmail.com','Admin','Annerson',1,1,3);
-- hospital reporter
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('reporter1','10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a','jaspercovidreporting2+reporter1@gmail.com','reporter1','Annerson',1,2,1);
-- GP reporter
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('reporter2','10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a','jaspercovidreporting+reporter2@gmail.com','reporter2','Annerson',1,2,4);
-- JCC recipient
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('recipient1','10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a','jaspercovidreporting+recipient1@gmail.com','recipient1','Annerson',1,3,2);
-- hospital recipient
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('recipient2','10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a','jaspercovidreporting+recipient2@gmail.com','recipient2','Annerson',1,3,1);

--Alpine village user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Alpine-Village-Jasper',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,2);
-- athabasca hotel user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Athabasca-Hotel',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,3);
--bear hill lodge user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Bear-Hill-Lodge',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,4);
--becker chaletes user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Beckers-Chaletes',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,5);
--cocos cafe user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Cocos-Cafe',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,6);
--Decore hotel user (m) user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Decore-Hotels-M',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,7);
--Decore hotel user (t) user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Decore-Hotels-T',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,8);
--Decore hotel user (w) user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Decore-Hotels-W',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,9);
--Jasper house bungalows user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Jasper-House-Bungalows',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,10);
--Jasper raft tours user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Jasper-Raft-Tours',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,11);
--Jasper sky tram user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Jasper-Sky-Tram',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,12);
--Jasper source for sports user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Jasper-Source-For-Sports',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,13);
--Journey bike guides user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Journey-Bike-Guides-INC',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,14);
--karouzos steakhouse user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Karouzos-Steakhouse',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,15);
--Liquor lodge 1 user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Liquor-Lodge-1',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,16);
--Liquor lodge 2 user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Liquor-Lodge-2',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,17);
--Maligne rafting adventure user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Maligne-Rafting-Adventures',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,18);
--Patricia lake bungalows user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Patricia-Lake-Bungalows',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,19);
--Royal canadian legion branch 31 user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Royal-Canadian-Legion-Branch-31',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,20);
--Snowdome coffee bar user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Snowdome-Coffee-Bar',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,21);
--Spa jasper user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Spa_Jasper',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,22);
--Tekarra restaurant user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Tekarra Restaurant',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,23);
--Mount robson inn user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Mount-Robson-Inn',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,24);
--Wildlife childcare user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Wildlife-Childcare',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,25);
--comunity outreach user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Community-Outreach',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,26);
--opes facility user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Operations-Facility',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,27);
-- bylaw user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Bylaw-Office',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,28);
--Jasper fitness and aqua user
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Jasper-Fitness-&-Aquatic-Center',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,29);
--Famoso
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`, `organisation`) VALUES ('Famoso',
            '10000:a8efdd18affeb4728641d4b2e6a8b10a:9b0cf110309909a2815b1980f51e29e4bf46d6dca76bce28430a8a5c4596a449631cfa3d2327f48b7958f8a7dac045847c296f146d91e7ce22a672787d8a501a',
            'cprg352+recipient2@gmail.com','recipient2','Annerson',1,2,30);






-- Covid test results
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2038-01-15', '2038-01-19', 1, 1, 100.00, 2);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2038-01-15', '2038-01-19', 4, 2, 50.00, 2);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2038-01-15', '2038-01-19', 9, 3, 33.33, 3);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2038-01-15', '2038-01-19', 9, 4, 44.44, 3);

INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 7, 2, 28.57, 7);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 10, 5, 50.00, 8);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 17, 6, 35.29, 9);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 45, 15, 33.33, 10);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 21, 13, 61.90, 11);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 11, 6, 54.54, 12);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 35, 14, 40.00, 13);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 41, 4, 09.75, 14);



INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-13', '2021-04-13', 0, 0, 0.0, 7);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-20', '2021-04-20', 5, 0, 0.0, 7);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-28', '2021-04-28', 9, 0, 0.0, 7);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-04', '2021-05-04', 5, 0, 0.0, 7);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-11', '2021-05-11', 12, 0, 0.0, 7);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-18', '2021-05-18', 5, 0, 0.0, 7);



INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 10, 5, 50.00, 8);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-13', '2021-04-13', 10, 4, 40.00, 8);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-20', '2021-04-20', 5, 1, 20.00, 8);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-28', '2021-04-28', 9, 0, 0.0, 8);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-04', '2021-05-04', 5, 3, 60.00, 8);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-11', '2021-05-11', 12, 1, 08.33, 8);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-18', '2021-05-18', 5, 0, 0.0, 8);

INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 17, 6, 35.29, 9);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-13', '2021-04-13', 17, 3, 17.64, 9);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-20', '2021-04-20', 17, 0, 0.0, 9);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-28', '2021-04-28', 9, 2, 22.22, 9);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-04', '2021-05-04', 9, 0, 0.0, 9);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-11', '2021-05-11', 6, 2, 33.33, 9);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-18', '2021-05-18', 5, 0, 0.0, 9);

INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 45, 15, 33.33, 10);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-13', '2021-04-13', 45, 10, 22.22, 10);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-20', '2021-04-20', 45, 0, 0.0, 10);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-28', '2021-04-28', 32, 3, 09.37, 10);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-04', '2021-05-04', 25, 0, 0.0, 10);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-11', '2021-05-11', 25, 0, 0.0, 10);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-18', '2021-05-18', 18, 4, 22.22, 10);

INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 21, 13, 61.90, 11);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-13', '2021-04-13', 21, 9, 42.85, 11);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-20', '2021-04-20', 21, 3, 14.28, 11);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-28', '2021-04-28', 16, 1, 06.25, 11);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-04', '2021-05-04', 10, 0, 0.0, 11);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-11', '2021-05-11', 12, 0, 0.0, 11);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-18', '2021-05-18', 8, 1, 01.25, 11);

INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 11, 6, 54.54, 12);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-13', '2021-04-13', 11, 3, 27.27, 12);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-20', '2021-04-20', 11, 0, 0.0, 12);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-28', '2021-04-28', 6, 1, 16.66, 12);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-04', '2021-05-04', 6, 0, 0.0, 12);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-11', '2021-05-11', 14, 4, 28.57, 12);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-18', '2021-05-18', 11, 0, 0.0, 12);

INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 35, 14, 40.00, 13);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-13', '2021-04-13', 35, 11, 31.42, 13);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-20', '2021-04-20', 35, 9, 25.71, 13);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-28', '2021-04-28', 27, 4, 14.81, 13);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-04', '2021-05-04', 21, 1, 04.76, 13);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-11', '2021-05-11', 17, 0, 0.0, 13);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-18', '2021-05-18', 11, 0, 0.0, 13);

INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-06', '2021-04-06', 41, 4, 09.75, 14);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-13', '2021-04-13', 41, 15, 36.58, 14);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-20', '2021-04-20', 41, 22, 53.65, 14);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-04-28', '2021-04-28', 37, 15, 40.54, 14);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-04', '2021-05-04', 39, 7, 17.94, 14);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-11', '2021-05-11', 41, 3, 07.31, 14);
INSERT INTO `covid_test_results` (`ResultDate`, `SubmissionDate`, `NumberTestsTaken`, `NumberTestsPositive`, `PositivityRate`, `ReporterID`) VALUES ('2021-05-18', '2021-05-18', 41, 1, 02.43, 14);

-- Covid reports
INSERT INTO `covid_reports` (`ReportDate`, `oneDayDifference`, `sevenDayDifference`, `fourteenDayDifference`, `totalCases`, `totalActiveCases`, `totalRecovered`, `totalDeaths`, `positivityRate`) VALUES ('2038-01-20', 1, 1, 1, 100, 1, 1, 1, 11.11);
INSERT INTO `covid_reports` (`ReportDate`, `oneDayDifference`, `sevenDayDifference`, `fourteenDayDifference`, `totalCases`, `totalActiveCases`, `totalRecovered`, `totalDeaths`, `positivityRate`) VALUES ('2021-04-06', 0, 0, 0, 210, 75, 0, 0, 35.71);
INSERT INTO `covid_reports` (`ReportDate`, `oneDayDifference`, `sevenDayDifference`, `fourteenDayDifference`, `totalCases`, `totalActiveCases`, `totalRecovered`, `totalDeaths`, `positivityRate`) VALUES ('2021-04-13', 0, 0, 0, 180, 55, 0, 0, 30.55);
INSERT INTO `covid_reports` (`ReportDate`, `oneDayDifference`, `sevenDayDifference`, `fourteenDayDifference`, `totalCases`, `totalActiveCases`, `totalRecovered`, `totalDeaths`, `positivityRate`) VALUES ('2021-04-20', 0, 0, 0, 180, 35, 0, 0, 19.44);
INSERT INTO `covid_reports` (`ReportDate`, `oneDayDifference`, `sevenDayDifference`, `fourteenDayDifference`, `totalCases`, `totalActiveCases`, `totalRecovered`, `totalDeaths`, `positivityRate`) VALUES ('2021-04-28', 0, 0, 0, 145, 25, 0, 0, 17.24);
INSERT INTO `covid_reports` (`ReportDate`, `oneDayDifference`, `sevenDayDifference`, `fourteenDayDifference`, `totalCases`, `totalActiveCases`, `totalRecovered`, `totalDeaths`, `positivityRate`) VALUES ('2021-05-04', 0, 0, 0, 114, 25, 0, 0, 09.64);
INSERT INTO `covid_reports` (`ReportDate`, `oneDayDifference`, `sevenDayDifference`, `fourteenDayDifference`, `totalCases`, `totalActiveCases`, `totalRecovered`, `totalDeaths`, `positivityRate`) VALUES ('2021-05-11', 0, 0, 0, 139, 10, 0, 0, 07.19);
INSERT INTO `covid_reports` (`ReportDate`, `oneDayDifference`, `sevenDayDifference`, `fourteenDayDifference`, `totalCases`, `totalActiveCases`, `totalRecovered`, `totalDeaths`, `positivityRate`) VALUES ('2021-05-18', 0, 0, 0, 104, 6, 0, 0, 05.76);





-- covid_report_recipients
INSERT INTO `covid_report_recipients` VALUES (1, 4);
INSERT INTO `covid_report_recipients` VALUES (1, 5);

INSERT INTO `covid_report_recipients` VALUES (2, 4);
INSERT INTO `covid_report_recipients` VALUES (2, 5);

INSERT INTO `covid_report_recipients` VALUES (3, 4);
INSERT INTO `covid_report_recipients` VALUES (3, 5);

INSERT INTO `covid_report_recipients` VALUES (4, 4);
INSERT INTO `covid_report_recipients` VALUES (4, 5);

INSERT INTO `covid_report_recipients` VALUES (5, 4);
INSERT INTO `covid_report_recipients` VALUES (5, 5);

INSERT INTO `covid_report_recipients` VALUES (6, 4);
INSERT INTO `covid_report_recipients` VALUES (6, 5);

INSERT INTO `covid_report_recipients` VALUES (7, 4);
INSERT INTO `covid_report_recipients` VALUES (7, 5);

-- covid_report_test_results
INSERT INTO `covid_report_covid_test_results` VALUES (1, 1);
INSERT INTO `covid_report_covid_test_results` VALUES (1, 2);
INSERT INTO `covid_report_covid_test_results` VALUES (1, 3);
INSERT INTO `covid_report_covid_test_results` VALUES (1, 4);

INSERT INTO `covid_report_covid_test_results` VALUES (2, 5);
INSERT INTO `covid_report_covid_test_results` VALUES (2, 6);
INSERT INTO `covid_report_covid_test_results` VALUES (2, 7);
INSERT INTO `covid_report_covid_test_results` VALUES (2, 8);
INSERT INTO `covid_report_covid_test_results` VALUES (2, 9);
INSERT INTO `covid_report_covid_test_results` VALUES (2, 10);
INSERT INTO `covid_report_covid_test_results` VALUES (2, 11);

INSERT INTO `covid_report_covid_test_results` VALUES (3, 12);
INSERT INTO `covid_report_covid_test_results` VALUES (3, 13);
INSERT INTO `covid_report_covid_test_results` VALUES (3, 14);
INSERT INTO `covid_report_covid_test_results` VALUES (3, 15);
INSERT INTO `covid_report_covid_test_results` VALUES (3, 16);
INSERT INTO `covid_report_covid_test_results` VALUES (3, 17);
INSERT INTO `covid_report_covid_test_results` VALUES (3, 18);
INSERT INTO `covid_report_covid_test_results` VALUES (3, 19);

INSERT INTO `covid_report_covid_test_results` VALUES (4, 20);
INSERT INTO `covid_report_covid_test_results` VALUES (4, 21);
INSERT INTO `covid_report_covid_test_results` VALUES (4, 22);
INSERT INTO `covid_report_covid_test_results` VALUES (4, 23);
INSERT INTO `covid_report_covid_test_results` VALUES (4, 24);
INSERT INTO `covid_report_covid_test_results` VALUES (4, 25);
INSERT INTO `covid_report_covid_test_results` VALUES (4, 26);
INSERT INTO `covid_report_covid_test_results` VALUES (4, 27);

INSERT INTO `covid_report_covid_test_results` VALUES (5, 28);
INSERT INTO `covid_report_covid_test_results` VALUES (5, 29);
INSERT INTO `covid_report_covid_test_results` VALUES (5, 30);
INSERT INTO `covid_report_covid_test_results` VALUES (5, 31);
INSERT INTO `covid_report_covid_test_results` VALUES (5, 32);
INSERT INTO `covid_report_covid_test_results` VALUES (5, 33);
INSERT INTO `covid_report_covid_test_results` VALUES (5, 34);
INSERT INTO `covid_report_covid_test_results` VALUES (5, 35);

INSERT INTO `covid_report_covid_test_results` VALUES (6, 36);
INSERT INTO `covid_report_covid_test_results` VALUES (6, 37);
INSERT INTO `covid_report_covid_test_results` VALUES (6, 38);
INSERT INTO `covid_report_covid_test_results` VALUES (6, 39);
INSERT INTO `covid_report_covid_test_results` VALUES (6, 40);
INSERT INTO `covid_report_covid_test_results` VALUES (6, 41);
INSERT INTO `covid_report_covid_test_results` VALUES (6, 42);
INSERT INTO `covid_report_covid_test_results` VALUES (6, 43);

INSERT INTO `covid_report_covid_test_results` VALUES (7, 44);
INSERT INTO `covid_report_covid_test_results` VALUES (7, 45);
INSERT INTO `covid_report_covid_test_results` VALUES (7, 46);
INSERT INTO `covid_report_covid_test_results` VALUES (7, 47);
INSERT INTO `covid_report_covid_test_results` VALUES (7, 48);
INSERT INTO `covid_report_covid_test_results` VALUES (7, 49);
INSERT INTO `covid_report_covid_test_results` VALUES (7, 50);
INSERT INTO `covid_report_covid_test_results` VALUES (7, 51);


-----Jagans imports
INSERT INTO covid_test_results (ResultDate, SubmissionDate, NumberTestsTaken, NumberTestsPositive, PositivityRate, ReporterID) VALUES ('2022-08-08', '2022-08-08', 23, 10, 43.47, 6);
INSERT INTO covid_test_results (ResultDate, SubmissionDate, NumberTestsTaken, NumberTestsPositive, PositivityRate, ReporterID) VALUES ('2022-08-08', '2022-08-08', 33, 8, 24.24, 7);
INSERT INTO covid_test_results (ResultDate, SubmissionDate, NumberTestsTaken, NumberTestsPositive, PositivityRate, ReporterID) VALUES ('2022-08-08', '2022-08-08', 25, 12, 48.00, 8);
INSERT INTO covid_test_results (ResultDate, SubmissionDate, NumberTestsTaken, NumberTestsPositive, PositivityRate, ReporterID) VALUES ('2022-08-08', '2022-08-08', 35, 16, 45.71, 9);
INSERT INTO covid_test_results (ResultDate, SubmissionDate, NumberTestsTaken, NumberTestsPositive, PositivityRate, ReporterID) VALUES ('2022-08-08', '2022-08-08', 10, 5, 50.00, 10);
INSERT INTO covid_test_results (ResultDate, SubmissionDate, NumberTestsTaken, NumberTestsPositive, PositivityRate, ReporterID) VALUES ('2022-08-08', '2022-08-08', 17, 6, 35.29, 11);
INSERT INTO covid_test_results (ResultDate, SubmissionDate, NumberTestsTaken, NumberTestsPositive, PositivityRate, ReporterID) VALUES ('2022-08-08', '2022-08-08', 21, 17, 80.95, 12);
INSERT INTO covid_test_results (ResultDate, SubmissionDate, NumberTestsTaken, NumberTestsPositive, PositivityRate, ReporterID) VALUES ('2022-08-08', '2022-08-08', 45, 15, 33.33, 13);