package com.sait.capstone.itsd.covidreporting.utilities;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.UnsupportedEncodingException;
import java.util.HashMap;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.List;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

/**
 * handles all functions relating to the sending of e-mails generated by system functions
 * @author Alex Hill
 */
public class EmailProviderService {

    /**
     * sends an e-mail using a specified template and a hashmap
     * @param to
     * @param subject
     * @param template
     * @param tags
     * @throws Exception 
     */
    public static void sendMail(String to, String subject, String template, HashMap<String, String> tags) throws Exception 
    {
        String body = "";
        try {
            // read whole template into a single variable (body)
            BufferedReader br = new BufferedReader(new FileReader(new File(template)));

            String line = br.readLine();
            while (line != null) {
                body += line;
                line = br.readLine();
            }

            // replace all {{variable}} with the actual values
            for (String key : tags.keySet()) {
                body = body.replace("{{" + key + "}}", tags.get(key));
            }

        } catch (Exception e) {
            Logger.getLogger(EmailProviderService.class.getName()).log(Level.SEVERE, null, e);
        }

        sendMail(to, subject, body, true);
    }
    
    /**
     * sends an e-mail using a specified template in string format
     * @param to
     * @param subject
     * @param body
     * @param bodyIsHTML
     * @throws MessagingException
     * @throws NamingException
     * @throws UnsupportedEncodingException 
     */
    public static void sendMail(String to, String subject, String body, boolean bodyIsHTML) throws MessagingException, NamingException, UnsupportedEncodingException 
    {
        Context env = (Context) new InitialContext().lookup("java:comp/env");
        String username = (String) env.lookup("webmail-username");
        String password = (String) env.lookup("webmail-password");
        String accountDisplayName = (String) env.lookup("webmail-displayName");

        Properties props = new Properties();
        props.put("mail.transport.protocol", "smtps");
        props.put("mail.smtps.host", "smtp.gmail.com");
        props.put("mail.smtps.port", 465);
        props.put("mail.smtps.auth", "true");
        props.put("mail.smtps.quitwait", "false");
        Session session = Session.getDefaultInstance(props);
        session.setDebug(false);

        // create a message
        Message message = new MimeMessage(session);
        message.setSubject(subject);
        if (bodyIsHTML) {
            message.setContent(body, "text/html");
        } else {
            message.setText(body);
        }

        // address the message
        Address fromAddress = new InternetAddress(username, accountDisplayName);
        Address toAddress = new InternetAddress(to);
        message.setFrom(fromAddress);
        message.setRecipient(Message.RecipientType.TO, toAddress);

        // send the message
        Transport transport = session.getTransport();
        transport.connect(username, password);
        transport.sendMessage(message, message.getAllRecipients());
        transport.close();
    }

    /**
     * Sends an e-mail to every recipient in the database to alert them to a new report being automatically generated.
     * @param recipientEmails List of strings containing all the e-mails for the recipients
     * @param emailSubjectLine The subject line for the e-mail
     * @param template The path of the template file for the e-mail
     * @param templateVariableMap A hash map filled with all variables contained within the template.
     * @throws MessagingException
     * @throws NamingException
     * @throws UnsupportedEncodingException 
     */
    public static void sendReportAlert(List<String> recipientEmails, String emailSubjectLine, String template, HashMap<String, String> templateVariableMap) throws MessagingException, NamingException, UnsupportedEncodingException
    {
        Context env = (Context) new InitialContext().lookup("java:comp/env");
        String username = (String) env.lookup("webmail-username");
        String password = (String) env.lookup("webmail-password");
        String accountDisplayName = (String) env.lookup("webmail-displayName");

        Properties props = new Properties();
        props.put("mail.transport.protocol", "smtps");
        props.put("mail.smtps.host", "smtp.gmail.com");
        props.put("mail.smtps.port", 465);
        props.put("mail.smtps.auth", "true");
        props.put("mail.smtps.quitwait", "false");
        Session session = Session.getDefaultInstance(props);
        session.setDebug(false);

        // create a message
        Message message = new MimeMessage(session);
        message.setSubject(emailSubjectLine);
        message.setContent(template, "text/html");

        // address the message
        Address fromAddress = new InternetAddress(username, accountDisplayName);
        message.setFrom(fromAddress);
        
        for (String email : recipientEmails)
        {
            Address toAddress = new InternetAddress(email);
            message.addRecipient(Message.RecipientType.BCC, toAddress);
        }       
        
        // send the message
        Transport transport = session.getTransport();
        transport.connect(username, password);
        transport.sendMessage(message, message.getAllRecipients());
        transport.close();
    }

    
}
